name: 機能追加リクエスト
description: サービスに新機能を追加したいとき
title: ''
labels: [ enhancement ]
assignees: 
body:
  - type: textarea
    attributes:
      label: 経緯・理由
      description: なぜこの内容を追加しようと思ったか？どんな話があったか？
      placeholder: 誰でもページ内容が確認できると、秘密情報を入れられない
  - type: textarea
    attributes:
      label: 追加内容詳細
      description: どんな機能を追加したいか?
      placeholder: メールアドレスでのログイン
    validations:
      required: true
  - type: textarea
    attributes:
      label: 完了要件
      description: どのような状態になったらこの issue が完了になるか？
      placeholder: |
        例：
        - ユーザーがメールアドレスとパスワードを使ってログインできる。
        - ログインしていないユーザーはログインページにリダイレクトする。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 手順
      description: 実装手順のアイデア
  - type: textarea
    attributes:
      label: その他の解決方法
      description: 提案した手順以外に、より良い方法があるか考えてみるエリア
