name: Codeball
on: [ pull_request ]

jobs:
  codeball_job:
    runs-on: ubuntu-latest
    name: Run Codeball
    steps:
      - name: Codeball AI Actions
        uses: sturdy-dev/codeball-action@v2
        with:
          approvePullRequests: "true"
          labelPullRequestsWhenApproved: "true"
          labelPullRequestsWhenReviewNeeded: "false"
          failJobsWhenReviewNeeded: "false"
