name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Cache build assets
        uses: actions/cache@v2
        with:
          path: .angular
          key: ${{ runner.os }}-ng-${{ hashFiles('src/**') }}
        restore-keys: |
          ${{ runner.os }}-ng-

      - run: npm ci && npm run build:prod

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FUKAGAWA_COFFEE }}"
          channelId: live
          projectId: fukagawa-coffee
